# Generated by Django 5.2.6 on 2026-01-20 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='marketplace.coachprofile')),
                ('job_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='marketplace.jobpost')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='marketplace.vendorprofile')),
            ],
            options={
                'unique_together': {('vendor', 'coach')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('vendor', 'Vendor'), ('coach', 'Coach')], max_length=10)),
                ('body', models.TextField()),
                ('contact_info_shared', models.BooleanField(default=False, help_text='Coach has shared contact info with this vendor')),
                ('read_by_vendor', models.BooleanField(default=False)),
                ('read_by_coach', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.thread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
