# Generated by Django 5.2.6 on 2025-11-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id_number', models.CharField(max_length=20)),
                ('last_name', models.TextField()),
                ('first_name', models.TextField()),
                ('res_street_number', models.TextField(blank=True)),
                ('res_street_name', models.TextField(blank=True)),
                ('res_apartment', models.TextField(blank=True)),
                ('res_zip', models.TextField(blank=True)),
                ('date_of_birth', models.TextField(blank=True)),
                ('date_of_registration', models.TextField(blank=True)),
                ('party', models.CharField(blank=True, max_length=2)),
                ('precinct', models.TextField(blank=True)),
                ('v20state', models.TextField(blank=True)),
                ('v21town', models.TextField(blank=True)),
                ('v21primary', models.TextField(blank=True)),
                ('v22general', models.TextField(blank=True)),
                ('v23town', models.TextField(blank=True)),
                ('voter_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
