# Generated by Django 5.2.6 on 2025-10-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_alter_photo_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
