# Generated by Django 5.2.6 on 2025-10-19 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0006_follow_follower_profile_follow_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_profile', to='mini_insta.profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='mini_insta.profile'),
        ),
    ]
