# Generated by Django 5.2.6 on 2026-01-20 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('state', models.CharField(default='MA', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('school_affiliation', models.CharField(blank=True, max_length=200)),
                ('grade_level', models.CharField(choices=[('hs', 'High School'), ('college', 'College'), ('other', 'Other')], max_length=10)),
                ('rating_rapid', models.IntegerField(blank=True, null=True)),
                ('rating_blitz', models.IntegerField(blank=True, null=True)),
                ('rating_bullet', models.IntegerField(blank=True, null=True)),
                ('rating_text', models.CharField(blank=True, help_text='Free text rating description', max_length=100)),
                ('years_experience', models.IntegerField(default=0)),
                ('age_groups_taught', models.CharField(blank=True, help_text='Comma-separated age group codes', max_length=50)),
                ('hourly_rate_min', models.IntegerField(blank=True, null=True)),
                ('hourly_rate_max', models.IntegerField(blank=True, null=True)),
                ('has_car', models.BooleanField(default=False)),
                ('max_travel_miles', models.IntegerField(default=10)),
                ('references_provided', models.BooleanField(default=False)),
                ('experience_with_schools', models.BooleanField(default=False)),
                ('tournament_director_experience', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='coach_photos/')),
                ('actively_looking', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='marketplace.coachprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CoachTown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coach_towns', to='marketplace.coachprofile')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.town')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('days_of_week', models.CharField(help_text='Comma-separated day numbers (0=Monday)', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('age_group', models.CharField(choices=[('k2', 'K-2'), ('35', '3-5'), ('68', '6-8'), ('912', '9-12')], max_length=10)),
                ('num_students', models.IntegerField()),
                ('pay_rate_min', models.IntegerField(blank=True, null=True)),
                ('pay_rate_max', models.IntegerField(blank=True, null=True)),
                ('requires_car', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.town')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='marketplace.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VendorCoachStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('contacted', 'Contacted'), ('interviewing', 'Interviewing'), ('hired', 'Hired'), ('not_a_fit', 'Not a Fit')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.coachprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.vendorprofile')),
            ],
            options={
                'unique_together': {('vendor', 'coach')},
            },
        ),
    ]
