# Generated by Django 5.2.6 on 2026-01-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorWaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('towns', models.CharField(help_text='Towns/areas they need coaches for', max_length=200)),
                ('needs_text', models.TextField(help_text="What they're looking for")),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vendor waitlist entries',
            },
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='availability',
            field=models.CharField(blank=True, help_text='Comma-separated: weekday_afternoon,weekday_evening,weekend', max_length=100),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='chesscom_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='lichess_username',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='rating_range',
            field=models.CharField(blank=True, choices=[('under1000', 'Under 1000'), ('1000-1400', '1000-1400'), ('1400-1800', '1400-1800'), ('1800-2200', '1800-2200'), ('2200+', '2200+'), ('unrated', 'Unrated/Casual')], max_length=20),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='teaching_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='town',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
