# Generated by Django 5.2.6 on 2025-11-26 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('grade', models.PositiveSmallIntegerField()),
                ('imlem_id', models.CharField(blank=True, help_text='Optional league ID or number.', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=200)),
                ('coach_name', models.CharField(max_length=100)),
                ('coach_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('strength_score', models.PositiveSmallIntegerField(help_text='Higher number = stronger in this category.')),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_strengths', to='project.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='project.team'),
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('opponent_league_name', models.CharField(blank=True, help_text='Optional: division / league / host info.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meets', to='project.team')),
            ],
        ),
        migrations.CreateModel(
            name='RoundAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(help_text='Individual round number (1–5).')),
                ('category_name', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('role', models.CharField(choices=[('COMPETE', 'Compete'), ('ALTERNATE', 'Alternate')], max_length=10)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Optional: points earned for this round.', null=True)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_assignments', to='project.meet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_assignments', to='project.student')),
            ],
            options={
                'unique_together': {('meet', 'student', 'round_number')},
            },
        ),
    ]
